<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Title>Bim4Everyone.RevitFiltration</Title>
        <PackageId>Bim4Everyone.RevitFiltration</PackageId>
        <Description>Данный пакет содержит базовые интерфейсы сервисов для фильтрации элементов в Autodesk Revit.</Description>
    </PropertyGroup>

    <!-- В библиотеке с контролами надо отображать десериализованный фильтр -->
    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Bim4Everyone.RevitFiltration.Controls</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>
</Project>
