<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <RuntimeIdentifiers>win-x64;win-x86</RuntimeIdentifiers>
        <EnableTUnitPolyfills>false</EnableTUnitPolyfills>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework> <!-- set default target framework -->
        <RevitVersion Condition="'$(RevitVersion)' == ''">2024</RevitVersion> <!-- set default revit version -->
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Nice3point.TUnit.Revit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Bim4Everyone.RevitFiltration\Bim4Everyone.RevitFiltration.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <GlobalPackageReference Remove="PolyFill"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Update="pyRevitLabs.Json">
            <Private>True</Private>
        </Reference>
        <Reference Update="dosymep.Revit">
            <Private>True</Private>
        </Reference>
        <Reference Update="dosymep.Bim4Everyone">
            <Private>True</Private>
        </Reference>
    </ItemGroup>
</Project>
