<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <UseWpf>true</UseWpf>
    </PropertyGroup>

    <PropertyGroup>
        <Title>Bim4Everyone.RevitFiltration.Controls</Title>
        <PackageId>Bim4Everyone.RevitFiltration.Controlss</PackageId>
        <Description>Данный пакет содержит WPF контролы для фильтрации элементов в Autodesk Revit.</Description>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="System.Web"/>
        <Reference Include="WindowsBase"/>
        <Reference Include="PresentationCore"/>
        <Reference Include="PresentationFramework"/>

        <PackageReference Include="WPF-UI" Version="4.0.0">
            <PrivateAssets>all</PrivateAssets>
            <ExcludeAssets>runtime</ExcludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.39">
            <PrivateAssets>all</PrivateAssets>
            <ExcludeAssets>runtime</ExcludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.WindowsAPICodePack-Shell" Version="1.1.0">
            <PrivateAssets>all</PrivateAssets>
            <ExcludeAssets>runtime</ExcludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Bim4Everyone.RevitFiltration\Bim4Everyone.RevitFiltration.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="dosymep.SimpleServices">
            <HintPath>$(AppData)\pyRevit\Extensions\BIM4Everyone.lib\dosymep_libs\libs\dosymep.SimpleServices.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="dosymep.WpfCore">
            <HintPath>$(AppData)\pyRevit\Extensions\BIM4Everyone.lib\dosymep_libs\libs\dosymep.WpfCore.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>
</Project>
