<Project>
    <PropertyGroup>
        <Platforms>x64</Platforms>
        <OutputType>Library</OutputType>
        <NoWarn>1701;1702;MSB3246</NoWarn>
        <TargetFramework>net48</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>12</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <RevitVersion Condition="'$(RevitVersion)' == ''">2024</RevitVersion>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
        <Configurations>D2020;D2021;D2022;D2023;D2024;Debug;Release</Configurations>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration.StartsWith(`D`))'">
        <Optimization>false</Optimization>
        <DebugSymbols>true</DebugSymbols>
        <OutputPath>bin\x64\Debug\$(RevitVersion)</OutputPath>
        <DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration.StartsWith(`R`))'">
        <Optimize>true</Optimize>
        <DebugSymbols>false</DebugSymbols>
        <OutputPath>bin\x64\Release\$(RevitVersion)</OutputPath>
        <DefineConstants>$(DefineConstants);RELEASE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="$(RevitVersion) != ''">
        <Version>$(RevitVersion).2.4</Version>
        <FileVersion>$(RevitVersion).2.4</FileVersion>
        <Company>Bim4Everyone</Company>
        <Authors>Bim4Everyone team</Authors>
        <PackageTags>Bim4Everyone, revit, plugins</PackageTags>
        <Copyright>Copyright © 2025</Copyright>
        <PackageProjectUrl>https://github.com/Bim4Everyone/Bim4Everyone.RevitFiltration.git</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Bim4Everyone/Bim4Everyone.RevitFiltration.git</RepositoryUrl>
        <RepositoryType>Git</RepositoryType>
    </PropertyGroup>

    <ItemGroup Condition="$(RevitVersion) != ''">
        <PackageReference Include="Autodesk.Revit.Sdk.Refs.$(RevitVersion)" Version="*">
            <PrivateAssets>all</PrivateAssets>
            <ExcludeAssets>runtime</ExcludeAssets>
        </PackageReference>

        <Reference Include="dosymep.Bim4Everyone">
            <HintPath>$(AppData)\pyRevit\Extensions\BIM4Everyone.lib\dosymep_libs\libs\$(RevitVersion)\dosymep.Bim4Everyone.dll</HintPath>
            <Private>False</Private>
        </Reference>

        <Reference Include="dosymep.Revit">
            <HintPath>$(AppData)\pyRevit\Extensions\BIM4Everyone.lib\dosymep_libs\libs\$(RevitVersion)\dosymep.Revit.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Ninject">
            <HintPath>$(AppData)\pyRevit\Extensions\BIM4Everyone.lib\Ninject.dll</HintPath>
            <Private>False</Private>
        </Reference>

        <Reference Include="pyRevitLabs.Json">
            <HintPath>$(AppData)\pyRevit-Master\bin\pyRevitLabs.Json.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>
</Project>